name: Build import-results

on:
  push:
  pull_request:
  # Every Monday 01:00 UTC
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

jobs:
  run:
    name: Build iocost-benchmarks-ci
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Checkoutm iocost-benchmarks-ci repository
        uses: actions/checkout@v4
        with:
          path: "iocost-benchmarks-ci"

      - name: Build ci-scripts
        run: cd ${GITHUB_WORKSPACE}/iocost-benchmarks-ci && cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iocost-benchmarks-ci
          if-no-files-found: error
          path: |
            iocost-benchmarks-ci/target/release/import-results
            iocost-benchmarks-ci/target/release/merge-results
            iocost-benchmarks-ci/config.toml

  # Keep workflow alive
  # See https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1.2.1
